### ISSUE TITLE
Mail unsubscribeToAdmin displays only mailaddress

### ISSUE THREAD

**Issue by jacques2017** [bihor/fp_newsletter#52]
Hi, in the mail unsubscribeToAdmin I need to display the first_name and last_name. But they are empty.
![grafik](https://user-images.githubusercontent.com/26480486/166476031-4123404b-a769-41df-a89b-1e9693acaa65.png)
In the Mail it looks like:

Guten Tag,

dieser User hat sich gerade vom Newsletter abgemeldet:

Name: [this is empty]

E-Mail: [the correct mailaddress is displayed]

Mit freundlichen Grüßen
Ihre Firma

I use direct_mail with tt_address , the newest Version of fp_newsletter and "unsubscribe with link" to unsubscribe. The missing fields (first_name, last_name) are filled in tt_address.

**Comment by bihor** [comment]
Well, I have noticed, that the name is empty in this email and therefore I removed the name in version 3.0.0 from that template.
Your output must be from an older version.

The problem is that there is no relation between a log-entry and an tt_address-entry.

OK, a solution could be:
- we know the uid from tt_address
- I could select all data from tt_address for the found uid: in the delete-action is this needed: getUserFromExternal($dbuidext, $table);
- copy the name to the log-entry. This could be done at line 466
- add the name again to the email-template unsubscribeToAdmin 

I could do it next week.

**Comment by jacques2017** [comment]
Thanks. 
Yes, the template is from an older Version, because I use a copy of the template.

**Comment by bihor** [comment]
OK, this is now implemented in version 3.0.2.

**Comment by jacques2017** [comment]
Many thanks.
In my template I added an <f:if ... > to check if lastname or firstname are empty or not.
